<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Form;
use Illuminate\Http\Request;
use Inertia\Inertia;
use Inertia\Response;

class FormController extends Controller
{
    /**
     * Display a listing of the forms.
     */
    public function index(Request $request): Response
    {
        $query = Form::query()->with('category')->withCount('submissions');

        // Filter by category
        if ($request->filled('category_id')) {
            $query->where('category_id', $request->category_id);
        }

        // Filter by status
        if ($request->filled('status')) {
            $query->where('is_active', $request->status === 'active');
        }

        // Search by title
        if ($request->filled('search')) {
            $query->where('title', 'like', '%' . $request->search . '%');
        }

        $forms = $query->latest()->paginate(10)->withQueryString();
        $categories = Category::active()->ordered()->get(['id', 'name', 'type']);

        return Inertia::render('Admin/Forms/Index', [
            'forms' => $forms,
            'categories' => $categories,
            'filters' => $request->only(['category_id', 'status', 'search']),
        ]);
    }

    /**
     * Show the form for creating a new form.
     */
    public function create(): Response
    {
        $categories = Category::active()->ordered()->get(['id', 'name', 'type']);

        return Inertia::render('Admin/Forms/Create', [
            'categories' => $categories,
        ]);
    }

    /**
     * Store a newly created form in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'category_id' => 'required|exists:categories,id',
            'title' => 'required|string|max:255',
            'description' => 'nullable|string',
            'schema' => 'required|array',
            'schema.fields' => 'required|array|min:1',
            'is_active' => 'boolean',
        ]);

        // Slug will be auto-generated by model
        Form::create($validated);

        return redirect()->route('admin.forms.index')
            ->with('success', 'Form berhasil dibuat.');
    }

    /**
     * Show the form for editing the specified form.
     */
    public function edit(Form $form): Response
    {
        $categories = Category::active()->ordered()->get(['id', 'name', 'type']);

        return Inertia::render('Admin/Forms/Edit', [
            'form' => $form,
            'categories' => $categories,
        ]);
    }

    /**
     * Update the specified form in storage.
     */
    public function update(Request $request, Form $form)
    {
        $validated = $request->validate([
            'category_id' => 'required|exists:categories,id',
            'title' => 'required|string|max:255',
            'description' => 'nullable|string',
            'schema' => 'required|array',
            'schema.fields' => 'required|array|min:1',
            'is_active' => 'boolean',
        ]);

        $form->update($validated);

        return redirect()->route('admin.forms.index')
            ->with('success', 'Form berhasil diperbarui.');
    }

    /**
     * Remove the specified form from storage.
     */
    public function destroy(Form $form)
    {
        // Check if form has submissions
        if ($form->submissions()->count() > 0) {
            return back()->with('error', 'Form tidak dapat dihapus karena masih memiliki pengajuan.');
        }

        $form->delete();

        return redirect()->route('admin.forms.index')
            ->with('success', 'Form berhasil dihapus.');
    }

    /**
     * Toggle the active status of the form.
     */
    public function toggleStatus(Form $form)
    {
        $form->update(['is_active' => !$form->is_active]);

        return back()->with('success', 'Status form berhasil diubah.');
    }
}
